[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
capstone_harshit = "EKAaTiK6Fg19wAy9FGXTC171ZtkPCdiK7zrfQ47px5Cf"

[programs.devnet]
capstone_harshit = "EKAaTiK6Fg19wAy9FGXTC171ZtkPCdiK7zrfQ47px5Cf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/titan/Desktop/capstone-harshit/harshit.json"


[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"